sqlite3:
  adapter: sqlite3
  database: acts_as_has_default.sqlite3.db
sqlite3mem:
  :adapter: sqlite3
  :database: ":memory:"
postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: acts_as_has_default_plugin_test
  :min_messages: ERROR
mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password:
  :database: acts_as_has_default_plugin_test